### ISSUE TITLE
middleware/populateVisualization could not find executions for the query

### ISSUE THREAD

**Issue by CCMcGuinness** [PDCbc/queries#51]
this error message received (Jan 11) for the following queries
PDC 001
PDC 1740
PDC 1901
PDC 943
PDC 1921 thru 1930
PDC 732

**Comment by CCMcGuinness** [comment]
PDC 001 - sometimes this works - likely a result of work on retro attachment queries is impacting this
PDC 1740 - similar to above
PDC 1901 - pneumovaccine - part of Population Health prevention
PDC 943 - influenze vaccine - part of Population health prevention
series PDC 1921 thru 1930 are working now - I think this fix was related to something that wasn' captilized? not exactly sure
PDC 732 - part of Practice Reflection pain module....

**Comment by DerekRoberts** [comment]
PDC-001 had been cleared for retro testing and appears okay at the moment.
PDC-1740 is only counting 7705 encounters total for all doctors in the last month.
PDC-1901 not in job sets.  Just added, but still reporting no executions.
PDC-943 was mistyped  as 934.  Fixed.
PDC-1921 - 1930 are fine.
